baseURL = 'https://sonac.lol/'
languageCode = 'en-us'
title = 'My Blogo'
theme = "anatole"

summarylength = 10
enabileEmoji = true
enableRobotsTXT = true

pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntas = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe = true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
    includeNewer = true
    threshold = 80
    toLower = true
[[related.indicies]]
    name = 'keywords'
    weight = 100
[[related.indicies]]
    name = 'tags'
    weight = 100


copyright = "2022-{{ YEAR }}"