[build]
  publish = "public"
  command = "hugo --gc --minify"
  
[build.environment]
  HUGO_VERSION = "0.100.1"
  HUGO_ENV = "production"
  HUGO_THEME = "anatole"
  HUGO_BASEURL = "https://sonac.lol"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"